export const createData = async (req, res, next) => {
  try {
  } catch (error) {
    res.status(500).json({ status: false, msg: "catch err" });
  }
};
export const findAll = async (req, res, next) => {
  try {
  } catch (error) {
    res.status(500).json({ status: false, msg: "catch err" });
  }
};
export const findOne = async (req, res, next) => {
  try {
  } catch (error) {
    res.status(500).json({ status: false, msg: "catch err" });
  }
};
